#undef BST_AVL
#undef BST_bal
#undef BST_BAL
#undef BST_BAL_INC
#undef BST_BLK
#undef BST_CMP
#undef BST_ctx
#undef BST_CTX
#undef BST_E
#undef BST_ELL_LESS
#undef BST_KEY
#undef BST_KEY_QRY
#undef BST_KEY_T
#undef BST_LINK
#undef BST_LINKIN_REBALANCE
#undef BST_lkg
#undef BST_LKG
#undef BST_ln
#undef BST_LN
#undef BST_META
#undef BST_META_CPY
#undef BST_META_INIT
#undef BST_META_SWP
#undef BST_NODE
#undef BST_0
#undef BST_P
#undef BST_PR_INDENT
#undef BST_PR_NIL
#undef BST_PR
#undef BST_red
#undef BST_RED
#undef BST_SPLAY
#undef BST_UNLINK_REBALANCE
#undef BST_up
#undef BST_UP
#undef BST_WEIGHT
#undef BST_wt
#undef BST_WT
#undef BST_WT_INC
#undef BST_WT_UPDATE
